---
- name: provision
  remote_user: root
  hosts: all
  # Do not gather facts here because initially python2, an Ansible dependency is not installed
  gather_facts: false
  vars:
    - hostname: "goblin"
    - timezone: "America/Chicago"
    - main_user: bholt
    - gh_pubkey_user: bradyholt
    - media_device_uuid: "45BB-995F"
  # The following variables values are specified in secrets.yml.  When running ansible-playbook, "-e @secrets.yml" should be specified.
  # - main_user_password:
  # - nest_username:
  # - nest_password:
  # - nma_api_key:
  # - nma_url:  
  # - vistaicm_server_pound_commands:
  pre_tasks:
    - name: 'Install python2'
      raw: pacman -Sy --noconfirm --needed python2 && ln -sf /usr/bin/python2 /usr/bin/python
    - name: Gather facts
      setup: # Now gather facts: http://stackoverflow.com/a/31060268/626911
  roles:
    - hostname
    - timezone
    - user
    - { role: utils, tags: ['utils'] }
    - cron
    - node
    - vistaicm-server
    - { role: media-drive, tags: ['media-drive'] }
    - { role: insync, tags: ['insync'] }
    - { role: samba, tags: ['samba'] }
    - { role: dlna, tags: ['dlna'], movies_dir: 'Movies' }