---
- name: Install minidlna
  pacman: name=minidlna state=present

- name: Disable package minidlna unit
  systemd: enabled=no state=stopped name=minidlna

- name: Setup minidlna config file
  template:
    src: minidlna.conf.j2
    dest: /etc/minidlna.conf
  notify: restart mindlna-user

- name: Install minidlna systemd unit file
  template: src=minidlna.service.j2 dest=/etc/systemd/system/minidlna-user.service
  notify: restart mindlna-user